apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
   app: helloservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      serviceAccountName: default
      containers:
      - name: hello-container
        image: 'docker.io/darya2019/hello-from-cloud:latest'
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: ClusterIP
  selector:
    app: helloservice
  ports:
  - name: grpc
    port: 9555
    targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-external
spec:
  type: LoadBalancer
  selector:
   app: helloservice
  ports:
  - name: http
    port: 80
    targetPort: 8081